### PR TITLE
Adds beanstalkworker with context example

### PR DESCRIPTION
**Pull request by gha**
Adds a worker example that uses a signal handler to cancel the context and cleanly shutdown the worker.

Example is go installable inside the examples directory

### CODE REVIEW

**Comment by tomponline** [comment]
thanks @gha can you check that the examples folder and program within it as not built when using `go install ./...` and also what is the behaviour when using govendor and its ilk? Cheers

**Comment by tomponline** [comment]
@gha as far as I can make out, govendor ignores the examples folder, and if you do `go install` inside the beanstalkworker folder, it doesnt build and install the examples folder, but if you do `go install ./...` it does. Which is probably fine.

**Comment by gha** [comment]
@tomponline yes I've tested to double check, the examples are only installed if you run ```go install ./...```. Any packages referenced in the examples would be vendored (tested using govendor). The examples don't import anything other than the beanstalkworker though, so any external applications importing this wouldn't get any additional vendored packages

**Review by tomponline — APPROVED** [review]
thanks @gha

**Pull request merged**
