### PR TITLE
re-organises repo so that example code are part of testing framework

### PR DESCRIPTION
**Pull request by tomponline**
- Moves beanstalkworker package into root of repo
- Converts example program into example test

### CODE REVIEW

**Review by NevilleC — COMMENTED** [review]
looks good @tomponline but we should update the usage section of the README as well
https://github.com/tomponline/beanstalkworker#usage
as the `go get` command should be simplified.

**Comment by tomponline** [comment]
Agreed will do

**Comment by NevilleC** [comment]
I tested it by updating a repo I play with recently, and it seems to work well. It doesn't add the example go file as you wanted.

```bash
[root@ncel6 ict-billingjobs]# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   billingjobs/billingjobs.go
	modified:   billingjobs/billingjobs_test.go
	modified:   billingjobs/callbillingjob.go
	modified:   billingjobs/callbillingjob_test.go
	modified:   billingjobs/invoiceSaveJob.go
	modified:   billingjobs/invoiceSaveJob_test.go
	modified:   billingjobs/invoiceSendJob.go
	modified:   billingjobs/invoiceSendJob_test.go
	new file:   vendor/github.com/tomponline/beanstalkworker/CONTRIBUTING.md
	new file:   vendor/github.com/tomponline/beanstalkworker/README.md
	renamed:    vendor/github.com/tomponline/beanstalkworker/beanstalkworker/job.go -> vendor/github.com/tomponline/beanstalkworker/job.go
	renamed:    vendor/github.com/tomponline/beanstalkworker/beanstalkworker/logger.go -> vendor/github.com/tomponline/beanstalkworker/logger.go
	renamed:    vendor/github.com/tomponline/beanstalkworker/beanstalkworker/rawJob.go -> vendor/github.com/tomponline/beanstalkworker/rawJob.go
	renamed:    vendor/github.com/tomponline/beanstalkworker/beanstalkworker/worker.go -> vendor/github.com/tomponline/beanstalkworker/worker.go
	modified:   vendor/vendor.json
```

It does add the README and CONTRIBUTING markdown file, though, but I don't think this is a problem.

**Comment by tomponline** [comment]
@NevilleC yeah thats fine, cheers

**Comment by tomponline** [comment]
@NevilleC also note, when you re-vendor, make sure you pull in latest https://github.com/tomponline/beanstalk too as that has some network reliability fixes. https://github.com/tomponline/beanstalk/commit/40b3fd723514e22595e63d4e3d13bfdbc9c64650

**Pull request merged**
